services:
  general:
    build: .devcontainer/general
    container_name: general
    volumes:
      - ./:/workspace:cached,rw
      - /var/run/docker.sock:/var/run/docker.sock:cached
    tty: true
    stdin_open: true
    
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql:cached,rw
      - ./db/init:/docker-entrypoint-initdb.d:ro

  php:
    build: ./docker/php
    container_name: php
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    expose:
      - 9000

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - postgres
    ports:
      - 3000:8080
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/solitario.conf:/etc/nginx/conf.d/solitario.conf:ro


volumes:
  postgres_data:
    driver: local
